---

- name: i3 packages, dependencies and tools should be installed
  become: yes
  dnf: name={{ item }} state=latest
  with_items:
    - automake
    - cmake
    - dmenu
    - feh
    - fontawesome-fonts
    - gcc
    - gcc-c++
    - git
    - i3
    - i3lock
    - i3status
    - libev-devel
    - libxcb-devel
    - libXinerama-devel
    - libxkbcommon-devel
    - libxkbcommon-x11-devel
    - libXrandr-devel
    - pango-devel
    - pcmanfm
    - pcre-devel
    - scrot
    - startup-notification-devel
    - xbacklight
    - xcb-proto
    - xcb-util-cursor-devel
    - xcb-util-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - xcb-util-xrm-devel
    - yajl-devel

- name: i3 config folder should exist
  file: path={{ user.home }}/.i3 state=directory

- name: Tools repos should be cloned
  git: >
    repo={{ item.repo }}
    dest={{ user.home }}/.i3/{{ item.name }}
    recursive=yes
  with_items:
    - { name: i3blocks, repo: "https://github.com/vivien/i3blocks" }
    - { name: polybar, repo: "https://github.com/jaagr/polybar" }

- name: Checking i3blocks install
  stat: path=/usr/local/bin/i3blocks
  register: i3blocks_installed

- name: i3block should be built and installed
  become: yes
  make: chdir={{ user.home }}/.i3/i3blocks
  with_items:
    - clean
    - all
    - install
  when: i3blocks_installed.stat.exists == false

- name: Config files should be deployed
  copy: >
    src={{ item }}
    dest={{ user.home }}/.i3
  with_fileglob:
    - config/*

- name: i3 config files should belong to {{ user.name }}
  file:
    state: directory
    recurse: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    path: "{{ user.home }}/.i3"
