---

- name: Atom should be installed
  stat: path=/usr/bin/atom
  register: atom_installed

- name: Download Atom's RPM package from atom.io
  get_url: url=http://atom.io/download/rpm dest=/tmp/atom.rpm
  when: atom_installed.stat.exists == false

- name: Atom should be installed from atom.io's RPM package
  become: yes
  dnf: name=/tmp/atom.rpm state=present
  when: atom_installed.stat.exists == false

- name: APM should use proxy if needed
  template: >
    src=apmrc.j2
    dest="{{ user.home }}/.atom/.apmrc"
    owner="{{ user.name }}"
    group="{{ user.name }}"
  tags: proxy
  when: proxy is defined

- name: Asciidoc need to be installed for preview package
  become: yes
  dnf: name=asciidoc state=latest

- name: Atom packages should be installed
  include: atom-one-package.yml
  with_items:
    - asciidoc-preview
    - language-ansible
    - language-groovy
    - language-docker
    - pretty-json
    - tree-view-git-status
    - editorconfig
