---

- set_fact: docker_compose_version="1.8.0"
- set_fact: docker_machine_version="0.8.1"

# Engine
- name: Docker yum repo should be installed
  become: yes
  copy: src=docker.repo dest=/etc/yum.repos.d mode=644

- name: Docker package should be installed
  become: yes
  dnf: name=docker-engine state=latest
  notify:
    - restart docker

- name: A Docker group should exist
  become: yes
  group: name=docker state=present
  tags: fast

- name: Current user should belong to group Docker
  become: yes
  user: name="{{ user.name }}" groups=docker append=yes
  tags: fast

- name: Docker systemd droplet folder should exist
  become: yes
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: Proxy should be configured in Docker
  become: yes
  template: >
    src=proxy.conf.j2
    dest=/etc/systemd/system/docker.service.d/proxy.conf
    mode=600
  tags: proxy
  notify:
    - restart docker

- name: Docker should be enabled
  become: yes
  service: name=docker enabled=yes

# Compose
- name: Docker Compose v{{ docker_compose_version }} should be installed
  stat: path=/usr/bin/docker-compose-{{ docker_compose_version }}
  register: compose_installed
  changed_when: "compose_installed.stat.exists == false"

- name: Docker Compose v{{ docker_compose_version }} should be downloaded from github
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose-{{ docker_compose_version }}
  when: compose_installed.stat.exists == false

- name: Downloaded file should be executable
  become: yes
  file:
    path: /usr/bin/docker-compose-{{ docker_compose_version }}
    mode: 0755

- name: Docker Compose symlink should point to v{{ docker_compose_version }}
  become: yes
  file:
    src: /usr/bin/docker-compose-{{ docker_compose_version }}
    dest: /usr/bin/docker-compose
    state: link

# Machine
- name: Docker Machine v{{ docker_machine_version }} should be installed
  stat: path=/usr/bin/docker-machine-{{ docker_machine_version }}
  register: machine_installed
  changed_when: "machine_installed.stat.exists == false"

- name: Docker Machine v{{ docker_machine_version }} should be downloaded from github
  become: yes
  get_url:
    url: https://github.com/docker/machine/releases/download/v{{ docker_machine_version }}/docker-machine-Linux-x86_64
    dest: /usr/bin/docker-machine-{{ docker_machine_version }}
  when: machine_installed.stat.exists == false

- name: Downloaded file should be executable
  become: yes
  file:
    path: /usr/bin/docker-machine-{{ docker_machine_version }}
    mode: 0755

- name: Docker Machine symlink should point to v{{ docker_machine_version }}
  become: yes
  file:
    src: /usr/bin/docker-machine-{{ docker_machine_version }}
    dest: /usr/bin/docker-machine
    state: link
