---

- name: dnf should use proxy if needed
  become: yes
  template: >
    backup=yes
    src=dnf.conf.j2
    dest=/etc/dnf/dnf.conf
    owner=root
    group=root
  when: proxy is defined
  tags: proxy

- name: Basic packages should be installed
  become: yes
  dnf: name={{ item }} state=latest
  with_items:
    - ansible
    - aria2
    - git
    - htop
    - iftop
    - jq
    - kernel-devel
    - libselinux-python
    - nmon
    - openssh-server
    - python
    - python-pip
    - python2-dnf
    - subversion
    - the_silver_searcher
    - tmux
    - tree
    - vim

- name: SSHD should be enabled
  service:
    name: sshd
    state: started
    enabled: yes
