---

- name: Group wheel should exist
  group:
    name: wheel
    state: present

- name: Group wheel should be allowed to sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: "%wheel  ALL=(ALL)       ALL"

- name: User {{ user.name }} should exist
  become: yes
  user:
    name: "{{ user.name }}"
    home: "{{ user.home }}"
    password: "{{ user.password | password_hash('sha512') }}"
    update_password: on_create
    groups: wheel

- name: dnf should use proxy if needed
  become: yes
  template: >
    backup=yes
    src=dnf.conf.j2
    dest=/etc/dnf/dnf.conf
    owner=root
    group=root
  when: proxy is defined
  tags: proxy

- name: Basic packages should be installed
  become: yes
  dnf: name={{ item }} state=latest
  with_items:
    - ansible
    - aria2
    - git
    - htop
    - iftop
    - jq
    - kernel-devel
    - libselinux-python
    - nmon
    - openssh-server
    - psmisc
    - python
    - python-pip
    - python2-dnf
    - subversion
    - the_silver_searcher
    - tmux
    - tree
    - vim

- name: SSHD should be enabled
  service:
    name: sshd
    state: started
    enabled: yes
